# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-15 13:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import notification.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('is_notified', models.BooleanField(default=False, editable=False)),
                ('notification_attempts', models.PositiveIntegerField(default=0, editable=False)),
                ('notification_time', models.DateTimeField(blank=True, null=True)),
                ('callback_url', models.URLField(default='')),
                ('confirmation', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
                ('tx_hash', models.CharField(max_length=64)),
                ('tx', models.TextField(null=True)),
                ('address', models.CharField(default='', max_length=40)),
                ('block_height', models.DecimalField(decimal_places=0, max_digits=14, null=True)),
                ('block_hash', models.CharField(default='', max_length=64)),
                ('block', models.TextField(null=True)),
            ],
            options={
                'ordering': ('created_time',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddressSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('callback_url', models.URLField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=34, validators=[notification.validators.validate_address])),
                ('confirmation', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LastSeenBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('block_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-fA-F]{64}$')])),
            ],
        ),
        migrations.CreateModel(
            name='TxNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('is_notified', models.BooleanField(default=False, editable=False)),
                ('notification_attempts', models.PositiveIntegerField(default=0, editable=False)),
                ('notification_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TxSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('callback_url', models.URLField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('tx_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-fA-F]{64}$')])),
                ('confirmation_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'confirmation_count should be greater than 1')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='txnotification',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.TxSubscription'),
        ),
        migrations.AddField(
            model_name='addressnotification',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.AddressSubscription'),
        ),
    ]
