# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-06 08:07
from __future__ import unicode_literals

from django.db import migrations, models


def update_txout_spent(apps, schema_editor):
    TxOut = apps.get_model("explorer", "TxOut")
    db_alias = schema_editor.connection.alias
    TxOut.objects.using(db_alias).all().update(spent=False)
    TxOut.objects.using(db_alias).filter(tx_in__tx__block__in_longest=1)


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txout',
            name='spent',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(update_txout_spent),
    ]
