# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadir',
            name='blkfile_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datadir',
            name='blkfile_offset',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tx',
            name='hash',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='txin',
            name='txout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tx_ins', related_query_name='tx_in', to='explorer.TxOut'),
        ),
    ]
