# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['-time']},
        ),
        migrations.AlterField(
            model_name='txin',
            name='txout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tx_ins', related_query_name='tx_in', to='explorer.TxOut'),
        ),
    ]
